create table country
(
    id          bigint generated by default as identity primary key,
    name        varchar(255),
    continent   varchar(255)
);

create table author
(
    id          bigint generated by default as identity primary key,
    name        varchar(255),
    surname     varchar(255),
    country_id  bigint references country(id) on delete cascade
);

create table book
(
    id          bigint generated by default as identity primary key,
    name        varchar(255),
    category    varchar(255),
    availableCopies integer,
    author_id   bigint references author(id) on delete cascade
);

create table app_users
(
    username                   varchar(255) primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table user_wishlist
(
    user_username   varchar(255) references app_users(username),
    book_id         bigint references book(id),
    primary key (user_username,book_id)
);

CREATE TABLE user_rented_books (
    user_username varchar(255) references app_users(username),
    book_id bigint references book(id),
    primary key (user_username, book_id)
);